<?php
namespace Osynapsy\Csrf\Action;

use Osynapsy\Action\AbstractAction as ParentAction;
use Osynapsy\Csrf\Token;
use Osynapsy\Csrf\FormCsrf;


/**
 * Base action class providing CSRF protection for sensitive POST operations.
 *
 * This class extends the standard Osynapsy AbstractAction and adds a reusable
 * method `checkCsrf()` that validates nonce and token fields generated by
 * `FormCsrf::apply()`.
 *
 * Usage:
 *   - Call `$this->checkCsrf()` inside the `execute()` method of actions that
 *     require CSRF protection.
 *   - The method validates the presence and integrity of both `csrf_nonce`
 *     and `csrf_token` fields using the Token manager.
 *
 * If validation fails, an exception is raised and the action execution stops.
 *
 * This approach keeps CSRF checks explicit, avoids unnecessary overhead on
 * non-sensitive forms, and keeps the implementation simple and maintainable.
 *
 * @package Osynapsy\Csrf
 * @author Pietro Celeste <p.celeste@osynapsy.net>
 */

class AbstractAction extends ParentAction
{
    protected function checkCsrf($secretKey)
    {
        $nonce = $_POST[FormCsrf::FIELD_NONCE] ?? null;
        $token = $_POST[FormCsrf::FIELD_TOKEN] ?? null;
        if ($nonce === null || $token === null) {
            $this->raiseException('Invalid request.');
        }
        $csrf = new Token($secretKey);
        if (!$csrf->check($nonce, $token)) {
            error_log("CSRF FAIL on ".static::class." from IP ".($_SERVER['REMOTE_ADDR'] ?? 'unknown'));
            $this->raiseException('Invalid request.');
        }
        return true;
    }
}
