<?php
/**
 * Osynapsy CSRF Package
 *
 * Copyright (c) 2025 Pietro Celeste
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

namespace Osynapsy\Csrf\Action;

use Osynapsy\Action\AbstractAction as ParentAction;
use Osynapsy\Csrf\Token;
use Osynapsy\Csrf\FormCsrf;


/**
 * Base action class providing CSRF protection for sensitive POST operations.
 *
 * This class extends the standard Osynapsy AbstractAction and adds a reusable
 * method `checkCsrf()` that validates nonce and token fields generated by
 * `FormCsrf::apply()`.
 *
 * Usage:
 *   - Call `$this->checkCsrf()` inside the `execute()` method of actions that
 *     require CSRF protection.
 *   - The method validates the presence and integrity of both `csrf_nonce`
 *     and `csrf_token` fields using the Token manager.
 *
 * If validation fails, an exception is raised and the action execution stops.
 *
 * This approach keeps CSRF checks explicit, avoids unnecessary overhead on
 * non-sensitive forms, and keeps the implementation simple and maintainable.
 *
 * @package Osynapsy\Csrf
 * @author Pietro Celeste <p.celeste@osynapsy.net>
 */

class AbstractAction extends ParentAction
{
    protected function checkCsrf($secretKey)
    {
        $nonce = $_POST[FormCsrf::FIELD_NONCE] ?? null;
        $token = $_POST[FormCsrf::FIELD_TOKEN] ?? null;
        if ($nonce === null || $token === null) {
            $this->raiseException('Invalid request.');
        }
        $csrf = new Token($secretKey);
        if (!$csrf->check($nonce, $token)) {
            error_log("CSRF FAIL on ".static::class." from IP ".($_SERVER['REMOTE_ADDR'] ?? 'unknown'));
            $this->raiseException('Invalid request.');
        }
        return true;
    }
}
